services:
  # Backend API Service
  - type: web
    name: collaboard-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && mkdir -p logs
    startCommand: cd server && chmod +x start.sh && ./start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://collaboard-frontend.vercel.app,https://collaboard-frontend.vercel.app/
